version: "3.7"

services:
  web:
    build: .
    image: wlgus5704/ossprac
    volumes:
      - "./app:/app"
    ports:
      - "5000:80"
production:
    image: wlgus5704/ossprac:latest
    ports: 
      - "5000:80"
