node {
	git poll: true, url:'https://github.com/CSID-DGU/2022-1-OSSPrac-winner-8.git'
	withCredentials([[$class: 'UsernamePasswordMultiBinding',
	credentialsId: 'docker-hub',
	usernameVariable: 'DOCKER_USER_ID',
	passwordVariable: 'DOCKER_USER_PASSWORD']]) {
		stage('Pull') {
			git 'https://github.com/CSID-DGU/2022-1-OSSPrac-winner-8.git'
		}
		stage('Unit Test') {
		}
		stage('Build') {
			sh(script: 'docker-compose build web')
		}
		stage('Tag') {
			sh(script: '''docker tag ${DOCKER_USER_ID}/week4 \
			${DOCKER_USER_ID}/week4:${BUILD_NUMBER}''')
		}
		stage('Push') {
			sh(script: 'docker login -u ${DOCKER_USER_ID} -p ${DOCKER_USER_PASSWORD}')
			sh(script: 'docker push ${DOCKER_USER_ID}/week4:${BUILD_NUMBER}')
			sh(script: 'docker push ${DOCKER_USER_ID}/week4:latest')
		}
		stage('Deploy') {
			sh(script: 'docker-compose up -d production')
		}
		}
	}